apiVersion: v1
kind: Secret
metadata:
  name: nebius-secret
type: Opaque
stringData:
  NEBIUS_ENABLED: "0"
  NEBIUS_SERVICE_ACCOUNT_CREDS: |
    <service-account-file-content>
  NEBIUS_USER: <nebius-user>
  NEBIUS_PARENT_ID: <nebius-parent-id>
  NEBIUS_TENANT_ID: <nebius-tenant-id>
  NEBIUS_SERVICE_ACCOUNT_ID: <nebius-service-account-id>
  NEBIUS_SUBNET_ID: <nebius-subnet-id>
  NEBIUS_INSTANCE_NAME_PREFIX: job-queue-worker
  NEBIUS_IDLE_TIMEOUT_SECONDS: "600"
  HF_TOKEN: <hugging-face-token>
