apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: harbor-storage
    component: rustfs
  name: harbor-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: gp3
  volumeMode: Filesystem
