apiVersion: v1
kind: Secret
metadata:
  labels:
    app: harbor-storage
    component: rustfs
  name: harbor-storage
type: Opaque
stringData:
  STORAGE_ACCESS_KEY: storageadmin
  STORAGE_SECRET_KEY: changeme
