apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-agent
  labels:
    app: harbor
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harbor-agent-anyuid
  labels:
    app: harbor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: harbor-agent
