apiVersion: v1
kind: Secret
metadata:
  name: intake-poller-secret
type: Opaque
stringData:
  GOOGLE_SHEET_ID: <google-sheet-id>
  JOB_QUEUE_URL: https://job-queue-service
  AUTO_APPROVE: "false"
  ALLOW_INSECURE_QUEUE_HTTP: "false"
  service-account.json: |-
    <service-account-content>
